services:
  proxy:
    image: nginx:1.23.2
    ports:
      - 8080:80/tcp
    configs:
      - source: proxy_conf
        target: /etc/nginx/conf.d/default.conf
        uid: '0'
        gid: '0'
        mode: 0644

  web:
    build: ./web
    ports:
    - 3000:3000/tcp
    volumes:
    - ./web/src:/app/src:ro

  api:
    build: ./api
    ports:
      - 3030:5000/tcp
    volumes:
    - ./api/src:/app/src:ro

  db:
    image: postgres:15.0
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgres/data

  adminer:
    image: adminer:4.8.1

volumes:
  db_data: {}

configs:
  proxy_conf:
    file: ./nginx/nginx.conf
