services:
  proxy:
    image: nginx:1.23.2
    ports:
      - 8080:80/tcp
    configs:
      - source: proxy_conf
        target: /etc/nginx/conf.d/default.conf
        uid: '0'
        gid: '0'
        mode: 0644

  web:
    build: ./web
    ports:
      - 3000:3000/tcp
    volumes:
    - ./web/src:/app/src:ro

  api:
    build: ./api
    environment:
      APP_MODE: development
      DB_DIALECT: postgres
      DB_HOST: db
      DB_NAME: db
      DB_USER: postgres
      DB_PASS: secret
    volumes:
    - ./api/src:/app/src:ro

  db:
    image: postgres:15.0
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    ports:
      - 5432:5432/tcp
    volumes:
      - db_data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.3
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: db
    ports:
      - 3306:3306/tcp
    volumes:
      - maria_data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1

volumes:
  db_data: {}
  maria_data: {}

configs:
  proxy_conf:
    file: ./nginx/nginx.conf
