name: Build Docker Images CI

on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: metaweb
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ secrets.DOCKER_HUB_NS }}/hikeblog-web
          tags: |
            type=sha,event=branch,prefix={{branch}}-
            type=sha,event=pr,prefix={{branch}}-

      - name: Extract metadata (tags, labels) for Docker
        id: metaapi
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ secrets.DOCKER_HUB_NS }}/hikeblog-api
          tags: |
            type=sha,event=branch,prefix={{branch}}-
            type=sha,event=pr,prefix={{branch}}-

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: web
          file: ./web/Dockerfile.prod
          push: true
          tags: ${{ steps.metaweb.outputs.tags }}
          labels: ${{ steps.metaweb.outputs.labels }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: api
          file: ./api/Dockerfile.prod
          push: true
          tags: ${{ steps.metaapi.outputs.tags }}
          labels: ${{ steps.metaapi.outputs.labels }}
