name: Build Docker Images CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Web image
        run: docker build web --file web/Dockerfile.prod --tag hikeblog-web:$(date +%s)

      - name: Build the Api image
        run: docker build api --file api/Dockerfile.prod --tag hikeblog-api:$(date +%s)
