name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: bash ./utils/lint.sh

    - name: Store results output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint-output
        path: results.txt
