# FROM --platform=$BUILDPLATFORM node:18.2.0 as build
FROM node:18.2.0 as build

ENV NODE_ENV=production

WORKDIR /build
COPY package.json ./
COPY package-lock.json ./
RUN npm ci

COPY ./public ./public
COPY ./src ./src
RUN npm run build

################################################################################

# FROM --platform=$BUILDPLATFORM nginx:1.23.2
FROM nginx:1.23.2

ENV NODE_ENV=production

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
COPY --from=build /build/build/ .
